services:
  node_app:
    build:
      context: ./
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:12.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: seqwdhpiixscbv
      POSTGRES_PASSWORD: Postgres@Bolsa
      POSTGRES_DB: bolsa
    ports:
      - "5432:5432"

