services:
  node_app:
    build:
      context: ./
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:12.4
    volumes:
      - ./lumi.bkp:/docker-entrypoint-initdb.d/lumi.sql
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lumi
    ports:
      - "5432:5432"

